name: Flutter CD

on:
  push:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./cocopassflutter

  build_ios:
    name: Build Flutter (iOS)
    needs: [install_dependencies]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
      - run: flutter pub get
        working-directory: ./cocopassflutter
      - run: flutter clean
        working-directory: ./cocopassflutter
      - run: flutter build ios --no-codesign
        working-directory: ./cocopassflutter

  build_apk:
    name: Build Flutter (Android)
    needs: [install_dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
      - run: flutter pub get
        working-directory: ./cocopassflutter
      - run: flutter clean
        working-directory: ./cocopassflutter
      - run: flutter build apk
        working-directory: ./cocopassflutter
