name: Flutter CI

on:
    pull_request:
        branches:
            - dev
            
jobs:
    flutter_test:
        name: Test et analyse flutter
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: '3.13.0'
                channel: 'stable'
            
            - name: Get dependencies
              run: flutter pub get
              working-directory: ./cocopassflutter
        
            - name: Flutter analyze
              run: flutter analyze
              working-directory: ./cocopassflutter
        
            - name: Run Flutter tests
              run: flutter test
              working-directory: ./cocopassflutter
